"""add patterns

Revision ID: 3280fb1489c7
Revises: 07bff07e7f15
Create Date: 2025-09-05 17:35:48.842357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3280fb1489c7'
down_revision: Union[str, Sequence[str], None] = '07bff07e7f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_start_date_time', sa.DateTime(), nullable=False),
    sa.Column('pattern_end_date_time', sa.DateTime(), nullable=False),
    sa.Column('pattern_time_frame', sa.String(), nullable=False),
    sa.Column('symbol_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pattern')
    # ### end Alembic commands ###
