"""pattern - patterngroup - symbol

Revision ID: 3588779600ca
Revises: f4a6ad546508
Create Date: 2026-02-01 17:50:19.327700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3588779600ca'
down_revision: Union[str, Sequence[str], None] = 'f4a6ad546508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('quote_currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_group_id', sa.Integer(), nullable=False),
    sa.Column('pattern_first_candle', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pattern_last_candle', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('time_frame', sa.Enum('M1', 'M5', 'M15', 'H1', 'H4', 'Daily', 'Weekly', 'Monthly', name='timeframeenum'), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pattern_group_id'], ['pattern_groups.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patterns')
    op.drop_table('symbols')
    op.drop_table('pattern_groups')
    # ### end Alembic commands ###
