"""make pattern_group.name unique

Revision ID: 3a0839c11fa5
Revises: 3588779600ca
Create Date: 2026-02-17 17:10:59.411306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0839c11fa5'
down_revision: Union[str, Sequence[str], None] = '3588779600ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pattern_groups', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pattern_groups', type_='unique')
    # ### end Alembic commands ###
