"""add config table

Revision ID: cab32838f107
Revises: dd7b3b3345a6
Create Date: 2026-01-29 16:18:16.442118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab32838f107'
down_revision: Union[str, Sequence[str], None] = 'dd7b3b3345a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_datetime', sa.DateTime(), nullable=False),
    sa.Column('maximum_risk_percentage', sa.Float(), nullable=False),
    sa.Column('default_risk_percentage', sa.Float(), nullable=False),
    sa.Column('total_balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configs')
    # ### end Alembic commands ###
