"""init db

Revision ID: dd7b3b3345a6
Revises: 
Create Date: 2026-01-27 16:27:42.191747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7b3b3345a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('is_first_run', sa.Boolean(), nullable=False),
    sa.Column('is_development', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flags')
    # ### end Alembic commands ###
